### ISSUE TITLE
CSS `font` should be treated specially.

### ISSUE THREAD

**Issue by deemstone** [EverledgerIO/postcss-automath#5]
This should not be automath.

```css
/* code from https://developer.mozilla.org/en/docs/Web/CSS/font */
/* Set the font size to 12px and the line height to 14px. Set the font family to sans-serif */
p { font: 12px/14px sans-serif }
```
now we got:
```css
p { font: 0.857143px sans-serif }
```
